### ISSUE TITLE
After closing [AAI Industry] Stone Foundation Configuration, gui button in the upper left corner switches incorrectly

### ISSUE THREAD

**Issue by Xiaoyan366** [0n0w1c/Foundations#6]
Error while running event Foundations::on_gui_click (ID 1)
Unknown sprite "tile/rough-stone-path"
stack traceback:
	[C]: in function '__newindex'
	__Foundations__/control.lua:91: in function 'update_button'
	__Foundations__/control.lua:142: in function <__Foundations__/control.lua:96>

**Comment by 0n0w1c** [comment]
Thank you very much for reporting the error.
Are you able to provide any steps to reproduce this error? I have not been successful.

**Comment by Xiaoyan366** [comment]
https://github.com/user-attachments/assets/9746de5b-8606-4569-a77c-a53114fe2f13

**Comment by Xiaoyan366** [comment]
> Thank you very much for reporting the error. Are you able to provide any steps to reproduce this error? I have not been successful.

please watch the video

**Comment by 0n0w1c** [comment]
Excellent, thank you. I will fix this.

**Comment by 0n0w1c** [comment]
Version 2.11.4 has been uploaded. Thank you again for reporting this issue.

**Comment by 0n0w1c** [comment]
A new version 2.11.5 uploaded, improved handling of this error.
Also now supports Space Age but limits Foundations actions to the Nauvis surface.
